{
 "title": "Monitoring Ingestion",
 "description": "Monitoramento da ingestão bronze",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: flex-start; height: 50px; border: 1px solid black; padding-top: 10px;\">\n  <img src=\"https://cdn.prod.website-files.com/627fe3133bae75e7bfbb9b2a/66c6c9ec336d4457d421d5ca_apache-airflow.png\" alt=\"Airflow Logo\" style=\"height: 35px; margin-right: 15px;\">\n  <span style=\"padding-top: 10px; text-align: center;\">Ingestion Bronze</span>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; height: 50px; border-bottom: 1px solid black;\">\n  <img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSrANg8m4SmLQHmPcHy215L6Wr6zZQa5JMAQ&s\" alt=\"Databricks Logo\" style=\"height: 40px; margin-right: 10px;\">\n  <span>Execução de job - Databricks</span>\n</div>"
   }
  },
  {
   "title": "Copy to server - Not execute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "3 - (sum(af_agg_ti_start_schedule_data_master{task_id=\"run_copy_clientes\"} or vector(0)) by (clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"run_copy_clientes_produtos\"} or vector(0)) by (produtos_clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"run_copy_produtos_bancarios\"} or vector(0)) by (produtos) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 1, "x": 4, "y": 2 },
   "options": {
    "content": "&nbsp;\n<span style=\"font-size: 42px;\">→</span>\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n<span style=\"font-size: 42px;\">→</span>\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n<span style=\"font-size: 42px;\">→</span>"
   }
  },
  {
   "title": "Move Cloud - Not execute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "3 - (sum(af_agg_ti_start_schedule_data_master{task_id=\"move_cloud_clientes\"} or vector(0)) by (clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"move_cloud_clientes_produtos\"} or vector(0)) by (produtos_clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"move_cloud_produtos_bancarios\"} or vector(0)) by (produtos) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 1, "x": 9, "y": 2 },
   "options": {
    "content": "&nbsp;\n<span style=\"font-size: 42px;\">→</span>\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n<span style=\"font-size: 42px;\">→</span>\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n<span style=\"font-size: 42px;\">→</span>"
   }
  },
  {
   "title": "Purge - Not execute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "3 - (sum(af_agg_ti_start_schedule_data_master{task_id=\"expurgo_clientes\"} or vector(0)) by (clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"expurgo_clientes_produtos\"} or vector(0)) by (produtos_clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"expurgo_produtos_bancarios\"} or vector(0)) by (produtos) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 1, "x": 14, "y": 2 },
   "options": {
    "content": "&nbsp;\n<span style=\"font-size: 42px;\">→</span>\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n<span style=\"font-size: 42px;\">→</span>\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n&nbsp;\n<span style=\"font-size: 42px;\">→</span>"
   }
  },
  {
   "title": "Ingestion Bronze - Not execute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "3 - (sum(af_agg_ti_start_schedule_data_master{task_id=\"ingestao_bronze_clientes\"} or vector(0)) by (clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"ingestao_bronze_clientes_produtos\"} or vector(0)) by (produtos_clientes) + sum(af_agg_ti_start_schedule_data_master{task_id=\"ingestao_bronze_produtos_bancarios\"} or vector(0)) by (produtos) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Failed - Last 24h",
   "type": "table",
   "description": "Gráfico que apresenta as tabelas que não tiveram sucesso em sua execução",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Ingestion_DataMaster_CL\n| where todatetime(metrics_datetime_execution_s) >= ago(24h)\n| where metrics_execution_succes_b == \"false\"\n| summarize Count = count() by metrics_table_name_s\n| project Table = metrics_table_name_s, Failed = toint(Count)\n",
      "resources": [
       "/subscriptions/91436e17-b4ee-47a3-b2b3-097d4a28b75b/resourceGroups/data_master/providers/Microsoft.OperationalInsights/workspaces/logsdatamaster"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Copy to server -  Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"run_copy_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"run_copy_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"run_copy_produtos_bancarios\"}) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Move Cloud - Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"move_cloud_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"move_cloud_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"move_cloud_produtos_bancarios\"}) or vector(0))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purge - Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"expurgo_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"expurgo_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"expurgo_produtos_bancarios\"}) or vector(0))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Bronze - Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"ingestao_bronze_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"ingestao_bronze_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"success\", task_id=\"ingestao_bronze_produtos_bancarios\"}) or vector(0))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Copy to server -  Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"run_copy_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"run_copy_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"run_copy_produtos_bancarios\"}) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Move Cloud - Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"move_cloud_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"move_cloud_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"move_cloud_produtos_bancarios\"}) or vector(0))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Purge - Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"expurgo_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"expurgo_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"expurgo_produtos_bancarios\"}) or vector(0))\n\n\n\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Bronze - Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"ingestao_bronze_clientes\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"ingestao_bronze_clientes_produtos\"}) or vector(0)) + \n(sum(af_agg_ti_finish{dag_id=\"schedule_data_master\", state=\"failed\", task_id=\"ingestao_bronze_produtos_bancarios\"}) or vector(0))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: flex-start; height: 100px; border: 1px solid black; padding-top: 10px;\">\n  Execução de job - Cloud\n</div>\n"
   }
  },
  {
   "title": "Ingestion Success Rate and Failures",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Ingestion_DataMaster_CL\n| extend ExecutionTime = todatetime(metrics_datetime_execution_s)\n| where todatetime(metrics_datetime_execution_s) >= ago(24h)\n| summarize \n    TotalExecucoes = count(),  \n    TotalFalhas = countif(metrics_execution_succes_b == false)\n",
      "resources": [
       "/subscriptions/91436e17-b4ee-47a3-b2b3-097d4a28b75b/resourceGroups/data_master/providers/Microsoft.OperationalInsights/workspaces/logsdatamaster"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Ingestion executions - 7d",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Ingestion_DataMaster_CL\n| where todatetime(metrics_datetime_execution_s) >= ago(7d)\n| summarize \n    True_Count = countif(metrics_execution_succes_b == \"true\"), \n    False_Count = countif(metrics_execution_succes_b == \"false\") \n  by metrics_table_name_s\n",
      "resources": [
       "/subscriptions/91436e17-b4ee-47a3-b2b3-097d4a28b75b/resourceGroups/data_master/providers/Microsoft.OperationalInsights/workspaces/logsdatamaster"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Average rows inserted per table",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Ingestion_DataMaster_CL\n| where todatetime(metrics_datetime_execution_s) >= ago(1d)\n| summarize Media_Linhas = avg(metrics_qtd_total_rows_insert_d) by metrics_table_name_s\n",
      "resources": [
       "/subscriptions/91436e17-b4ee-47a3-b2b3-097d4a28b75b/resourceGroups/data_master/providers/Microsoft.OperationalInsights/workspaces/logsdatamaster"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Number of alerts per table - 30d",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Ingestion_DataMaster_CL\n| where todatetime(metrics_datetime_execution_s) >= ago(30d)\n| extend ExecutionTime = todatetime(metrics_datetime_execution_s)\n| summarize Alertas = count() by metrics_alerta_b, metrics_table_name_s\n| where metrics_alerta_b == \"true\"",
      "resources": [
       "/subscriptions/91436e17-b4ee-47a3-b2b3-097d4a28b75b/resourceGroups/data_master/providers/Microsoft.OperationalInsights/workspaces/logsdatamaster"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Alert Duplicate Ingestion",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "Ingestion_DataMaster_CL\n| where todatetime(metrics_datetime_execution_s) >= ago(24h)\n| extend ExecutionTime = todatetime(metrics_datetime_execution_s)\n| where metrics_alerta_b == true\n| summarize Alertas = count() by metrics_table_name_s\n| project Table = metrics_table_name_s, CountDuplicate = toint(Alertas)\n\n",
      "resources": [
       "/subscriptions/91436e17-b4ee-47a3-b2b3-097d4a28b75b/resourceGroups/data_master/providers/Microsoft.OperationalInsights/workspaces/logsdatamaster"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  }
 ]
}