version: '3.9'

services:
  postgres:
    build:
      context: /postgres
    environment:
      POSTGRES_DB: "request_manager_product"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "11930143605"
    ports:
      - "5432:5432"
    deploy:
      mode: global
      restart_policy:
        condition: always
    networks:
      - mycustomnetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - shared-volume:/var/lib/postgresql/exports

  my-python-app:
    build:
      context: ./transfer
      dockerfile: Dockerfile
    container_name: my_python_container
    environment:
      AZURE_SAS_TOKEN: "sp=cw&st=2024-10-20T02:42:12Z&se=2026-10-20T10:42:12Z&spr=https&sv=2022-11-02&sr=c&sig=MaoRwZWwtKEx5vDafwkbeHkx1Rir6bWRYy0FB3OOs58%3D"
    depends_on:
      - postgres
    volumes:
      - shared-volume:/var/lib/postgresql/exports
    networks:
      - mycustomnetwork

volumes:
  postgres-data:
  shared-volume:

networks:
  mycustomnetwork:
    driver: bridge